name: CI - Build and Publish Artifact

on:
  push:
    branches:
      - dev
      - uat
      - prod

permissions:
  contents: write
  id-token: write
  actions: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Publish
        run: dotnet publish --configuration Release --output ./publish

      - name: Create ZIP Artifact
        run: |
          cd ./publish
          zip -r ../hello-world-app.zip .
          cd ..

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: hello-world-app
          path: ./hello-world-app.zip

      - name: Upload to GitHub Release (dev-latest)
        if: startsWith(github.ref, 'refs/heads/dev')
        uses: softprops/action-gh-release@v2
        with:
          tag_name: dev-latest
          name: Dev Build (Latest)
          files: ./hello-world-app.zip
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Upload to GitHub Release (dev-run)
        if: startsWith(github.ref, 'refs/heads/dev')
        uses: softprops/action-gh-release@v2
        with:
          tag_name: dev-${{ github.run_number }}
          name: Dev Build Run #${{ github.run_number }}
          files: ./hello-world-app.zip
          generate_release_notes: false
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
