name: CI - Build and Publish Artifact

on:
  push:
    branches: [ "dev", "uat", "prod" ]

permissions:
  contents: write    # 👈 required for creating releases
  id-token: write    # (optional, for OIDC deployments)
  actions: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Publish
      run: dotnet publish --configuration Release --output ./publish

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: hello-world-app
        path: ./publish

    - name: Upload to GitHub Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/heads/dev')
      with:
        tag_name: dev-latest
        name: Dev Build
        files: ./publish/**
        overwrite: true          # ✅ allow overwriting same assets on rerun
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
